### PR TITLE
WIP: Update .travis.yml, test on 0.3 & 0.4 for now

### PR DESCRIPTION
**Pull request by garborg**
I haven't had a chance to debug the segfault on 0.4 any more.

I've put this on a branch in the main repo in case anyone tries to get travis testing working on 0.4 again.

### CODE REVIEW

**Comment by tedsteiner** [comment]
FYI @garborg, I just rebased this branch onto master to take another look at it.

**Comment by tedsteiner** [comment]
The tests on this pass for 0.3 and get the same results for 0.4 as the older Travis build system, so I'm going to go ahead and merge this into master. This seems much more elegant than the previous travis file. I still hope to figure out how to fix that segfault on 0.4 someday, but it's tough when I've never managed to reproduce that problem locally.

**Comment by garborg** [comment]
Oh, I know, I bet the 'build failing' statuses triggered by the segfault are bugging you. Thanks for merging this.

**Comment by tedsteiner** [comment]
Yep, they drive me crazy. But at least it works on 0.3 for now.

**Pull request merged**
